import angular from 'angular';

// Import our app config files
import constants  from './config/app.constants';
import appConfig  from './config/app.config';
import appRun     from './config/app.run';
import 'angular-ui-router';
// Import our templates file (generated by Gulp)
import './config/app.templates';
// Import our app functionaity
import './auth';
import './components';
import './home';
import './layout';
import './services';
import './settings';
import './testeditor';


// Create and bootstrap application
const requires = [
  'ui.router',
  'templates',
  'app.auth',
  'app.components',
  'app.home',
  'app.layout',
  'app.services',
  'app.settings',
  'app.testeditor'
];

// Mount on window for testing
window.app = angular.module('app', requires);

angular.module('app').constant('AppConstants', constants);

angular.module('app').config(appConfig);

angular.module('app').run(appRun);

angular.bootstrap(document, ['app'], {
  strictDi: true
});
